### ISSUE TITLE
outgoing wire protocol - signing messages.

### ISSUE THREAD

**Issue by awb99** [zabirauf/icsharp#17]
on mono messages received by notebook throw errors because the hash field of the
wire message is empty.  Instead it should be signed with  HMAC digests.  

Message signing is easy to do; .net libraries support this out of the box.
I can write the signing part, what I am unclear of is:
1.  jupyter notebook --help-all  
   It appears that default behavior is not to sign anything, so why is it now wanting wire to be signed.
   There should be an off switch
2. What is the parameter to pass to jupyter in the commandline, to give it the public key
   that ICShwarp would use. 
3. does this happen on mono only or also with latest Jupyter version on windows/
   If it happens only on mono, then the relevant Cryptography libraries on mono are missing.
   I know that mono misses some of the .net libraries.
4. We should know precisely which data is fed into the HMAC function, because different
   line separators or spaces might fuck up the signing.
   IPython's example:
   digester = HMAC(key, digestmod=hashlib.sha256)
   # for each message
   
   d = digester.copy()
   for serialized_dict in (header, parent, metadata, content):
   d.update(serialized_dict)
   signature = d.hexdigest()

For Implementation  I would use is this :

using System.Security.Cryptography;
RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider())
HMACSHA256 hmac = new HMACSHA256(key))

**Comment by awb99** [comment]
This syntax works: -  different to the windows version though..

ipython notebook --KernelManager.kernel_cmd="['mono', '/usr/local/bin/myjupytertest/icsharp/Kernel/bin/Release/iCSharp.Kernel.exe', '{connection_file}']" --Session.key='' --Session.keyfile=''  --ip=10.1.9.5

**Comment by denfromufa** [comment]
Here is signing mechanism described here:

https://groups.google.com/forum/m/#!topic/jupyter/A7XJUSI-OHc

**Comment by takluyver** [comment]
1. The notebook's default behaviour is to sign messages, and expect signed messages back. The defaults in the help message are misleading - there isn't a default signing key, because the default is to generate a fresh key for each kernel we start. As you've found, there is an off switch, but we don't recommend doing that - message signing is an important security feature, and the off switch turns it off for all kernels.

2. Jupyter creates the key and gives it to the kernel in the connection file (which is readable only by the user running Jupyter).

3. It looks like the chocolatey install script disables message signing, so I would assume it's doing the same on Windows as on Mono.

4. The wire protocol includes four message parts that are serialised JSON data. Pass these four to the signing function exactly as you're going to send them. Jupyter will verify the signature before deserialising them, just based on the bytes received in those four message parts.

**Comment by gwenzek** [comment]
Even if it's not recommended, here is how you turn off the signing while it's not implemented in ICsharp

In order to disable the signing you have to modify `jupyter_notebook_config.py` (in `~/.jupyter`)
You just have to uncomment the following line:

    c.Session.key = ''
